import math

# 🧠 Paste the exact AI_W1 and AI_B1 arrays generated by the script above here:
AI_W1 = [0.25, -0.41, 0.18, -0.33, 0.12]
AI_B1 = -0.05


def simulate_desktop_inference(p1, p2, p3, p4, p5):
    """
    Implements the exact math pipeline inside the Pico W forward loop.
    Features: pH, Temperature, Turbidity_V, Dissolved_Oxygen, Distance_CM
    """
    # 1. Feature Normalization tracking standard hardware scale limits
    s_ph = (p1 - 0.0) / (14.0 - 0.0)
    s_temp = (p2 - 10.0) / (40.0 - 10.0)
    s_turb = (p3 - 0.0) / (3.3 - 0.0)
    s_do = (p4 - 0.0) / (10.0 - 0.0)
    s_dist = (p5 - 0.0) / (30.0 - 0.0)

    # 2. Dot Product: z = sum(X_i * W_i) + B
    z_out = (s_ph * AI_W1[0] + s_temp * AI_W1[1] + s_turb * AI_W1[2] +
             s_do * AI_W1[3] + s_dist * AI_W1[4]) + AI_B1

    # 3. Sigmoid Activation Layer with protection barriers
    probability = 1.0 / (1.0 + math.exp(-max(min(z_out, 10.0), -10.0)))
    return probability


print("=======================================================")
print("🔬 EXECUTING LOCAL MICROPYTHON INFERENCE SIMULATION CHECK")
print("=======================================================\n")

# Scenario Check A: Extreme Hazard profile input (High pH, low DO, muddy water boundary)
prob_danger = simulate_desktop_inference(8.92, 27.9, 0.92, 2.4, 10.7)
print(f"Test Case [ANOMALY LOGGED] -> Estimated Hazard Index: {prob_danger:.4f}")
print(
    f"System Decision Logic Output -> {'⚠️ ACTUATE PURGE/RELAYS' if prob_danger >= 0.70 else '✅ ENVIRONMENT CLEAN'}\n")

# Scenario Check B: Optimal profile input (Balanced parameters)
prob_safe = simulate_desktop_inference(7.20, 24.5, 1.10, 7.8, 10.7)
print(f"Test Case [SAFE RUN]       -> Estimated Hazard Index: {prob_safe:.4f}")
print(f"System Decision Logic Output -> {'⚠️ ACTUATE PURGE/RELAYS' if prob_safe >= 0.70 else '✅ ENVIRONMENT CLEAN'}")
print("=======================================================")